### ISSUE TITLE
Make a `Tag` struct

### ISSUE THREAD

**Issue by joshbeckman** [joshbeckman/readwise-ruby#5]
Instead of just having `tags` (on a `Highlight` or `Book`) expose an array of hashes, each element in the array should be an instance of `Readwise::Tag` struct.

**Comment by ajistrying** [comment]
Hello, Is this API still open for contributions? If so I'd like to start working on it, I can grab this one as a starter!

**Comment by joshbeckman** [comment]
Absolutely!
